context:
  name: portablexdr
  version: "4.9.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://people.redhat.com/~rjones/${{ name }}/files/${{ name }}-${{ version }}.tar.gz
  sha256: 5cf4bdd153cf4d44eaf10b725f451d0cfadc070b4b9a9ccfb64094b8f78de72c
  patches:
    # Apply patches below which were originally from UDA repository
    # to fix build issues on Windows and Meson support.
    # See https://github.com/ukaea/UDA/tree/main/extlib/portablexdr-4.9.1
    - add-meson-support.patch
    - port-from-uda.patch
    - add-def-module.patch

build:
  number: 1
  skip:
    - unix
  script:
    - if: win
      then: |
        meson setup build --prefix %LIBRARY_PREFIX% -Dbuildtype=release || exit /b 1
        meson install -C build || exit /b 1
      else: |
        meson setup build ${MESON_ARGS}
        meson install -C build
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - meson
    - ninja
    - pkg-config
  run_exports:
    - ${{ pin_subpackage('portablexdr', upper_bound="x.x.x") }}

tests:
  - package_contents:
      lib:
        - xdr
      include:
        - rpc/config.h
        - rpc/rpc.h
        - rpc/types.h
        - rpc/xdr.h
      files:
        - ${{ "Library/" if win }}lib/pkgconfig/portablexdr.pc

about:
  homepage: https://people.redhat.com/~rjones/portablexdr/
  summary: external data representation (XDR) library
  description: |
    External Data Representation (XDR) is a technical standard format for data serialization, for uses such as computer network protocols.
    It allows data to be transferred between different kinds of computer systems.
  license: LGPL-2.0-or-later
  license_file: COPYING
  documentation: https://people.redhat.com/~rjones/portablexdr/
  repository: http://git.annexia.org/git/portablexdr.git

extra:
  recipe-maintainers:
    - munechika-koyo
